config/routes.rb
CryptidTracker::Application.routes.draw do
  devise_for :users
  resource :sightings

  root to: 'pages#map'
end

app/models/sighting.rb
class Sighting <ActiveRecord::Base
  belongs_to :user

  validates :name, :presence => true
  validates :latitude, :presence => true
  validates :longitude, :presence => true
  validates :user_id, :presence => true
  validates :description, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :sightings
  validates :email, :presence => true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
    def authorize
    redirect_to login_url, alert: "Not authorized" if current_user.nil?
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def map

  end
end

app/controllers/sightings_controller.rb
class SightingsController < ApplicationController

  before_filter :authorize, only: [:edit, :update, :destroy]

  def new
    @sighting = Sighting.new
    @sightings = Sighting.all
  end

  def create
    @sighting = Sighting.new(sighting_params)
    if @sighting.save
       redirect_to :back, notice: "Thank you for reporting your sighting"
    else
      redirect_to :back, alert:  "Something went wrong. Try again."
    end
  end

  def index
    @sightings = Sighting.all

  end

  def show
    @sighting = Sighting.find(params[:id])
  end

 def edit
    @sighting = Sighting.find(params[:id])
  end

  def update
    @sighting = Sighting.find(params[:id])
    if @sighting.update(:latitude => params[:latitude],
                        :longitude => params[:longitude],
                        :name => params[:name])
      redirect_to :back
    else
      redirect_to :back
    end
  end

  private
    def sighting_params
      params.require(:sighting).permit(:name, :user_id, :description, :latitude, :longitude)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
    redirect_to root_url, notice: "Thank you for signing up!"
    else
      render "new"
    end
  end

  def show
    @user = current_user
    @products = Product.all
  end

  private
    def user_params
     params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_header.html.erb
<div id="header" class="nav navbar navbar-fixed-top">
  <ul class="nav navbar-nav navbar-left">
    <li><%= link_to "Cryptid Tracker", root_path %></li>
  </ul>
  <ul class="header nav navbar-nav pull-right">
    <% if user_signed_in? %>
      <li><%= link_to "New Sighting", new_sightings_path %></li>

      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.email  %><b class="caret"></b></a>
        <ul class="dropdown-menu">
          <button><%= link_to 'Edit profile', edit_user_registration_path %></button>
          <button><%= link_to "Logout", destroy_user_session_path, method: :delete %></button>
        </ul>
      </li>
      <% else %>
      <button>
        <%= link_to "Sign up", new_user_registration_path %>
      </button>
      <button>
        <%= link_to "Login", new_user_session_path %>
      </button>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= content_for?(:title) ? yield(:title)+" | CryptidTracker" : "CryptidTracker" %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=AIzaSyD-mY93-KPr7OLzxyDCLSWz4_JTZSz8agg&sensor=false", "application", "data-turbolinks-track" => true %>
  <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

</head>
  <body>

    <%= render "layouts/header" %>

    <%= yield %>

  </body>

</html>

app/views/pages/map.html.erb
<div class="container main-heading">
 <h1 class="brand-heading">Cryptid Tracker</h1>
 <h3 class="brand-sub">Track Anomolies Worldwide</h3>
</div>
<div id="map-canvas"></div>

app/views/sightings/_form.html.erb
<% content_for(:title, "New Sighting") %>
<%= form_for @sighting do |f| %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <div class="form-group">
    <%= f.label :Cryptid_type %><br>
    <%= f.text_field :name, :class => "form-control blue-back"%>
  </div>

  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, :class => "form-control blue-back"%>
  </div>

  <div class="form-group">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude, :class => "form-control blue-back"%>
  </div>

  <div class="form-group">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude, :class => "form-control blue-back" %>
  </div><br>

  <%= f.submit(:class => "btn btn-primary")%>

<% end %>

app/views/sightings/index.html.erb
<h1>Here is a list of your sightings:</h1>

<ul>

<% @sightings.each do |s|%>
  <li>
      <% s.name%>, <% s.latitude%> <% s.longitude%>
  </li>

<% end %>
</ul>

app/views/sightings/new.html.erb
<div class="container main-container new-cryptid">
  <div class="row">
    <div class="form-box col-sm-5">
      <h3>Enter Your Cryptid Sighting:</h3>

      <%= render "form" %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    </div>
    <div class="cryptid-list col-sm-5">
      <h3>Current Cryptids:</h3>
      <ul>
        <% if @sightings.any? %>
        <% @sightings.each do |cryptid| %>
        <li><%= cryptid.name %></li>
          <% end %>
          <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<h1>Index</h1>